In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL 설정
base_url = "https://www.transfermarkt.com/spieler-statistik/wertvollstespieler/marktwertetop"
params = {
    "land_id": "0",
    "ausrichtung": "Torwart",
    "spielerposition_id": "1",
    "altersklasse": "o34",
    "jahrgang": "0",
    "kontinent_id": "0",
    "page": 1  # 페이지 번호 추가
}
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
}

# 데이터를 저장할 리스트 생성
players = []

# 여러 페이지 크롤링
while len(players) < 50:
    response = requests.get(base_url, headers=headers, params=params)

    # 상태 코드 확인
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, "html.parser")

        # 테이블 찾기
        table = soup.find("table", class_="items")

        if table:
            rows = table.find_all("tr", class_=["odd", "even"])
            for row in rows:
                if len(players) >= 50:
                    break

                # 선수 이름
                name_tag = row.find("td", class_="hauptlink")
                name = name_tag.a.get_text(strip=True) if name_tag and name_tag.a else "N/A"

                # 소속팀
                team_tag = row.find_all("td", class_="zentriert")[2]
                team = team_tag.img["alt"] if team_tag and team_tag.img else "N/A"

                # 국적
                nationality_tag = row.find("img", class_="flaggenrahmen")
                nationality = nationality_tag["alt"] if nationality_tag else "N/A"

                # 나이
                age_tag = row.find_all("td", class_="zentriert")[1]  # 두 번째 "zentriert" 클래스가 나이 열임
                age = age_tag.get_text(strip=True) if age_tag else "N/A"

                # 시장 가치
                market_value_tag = row.find("td", class_="rechts hauptlink")
                market_value = market_value_tag.get_text(strip=True) if market_value_tag else "N/A"

                # 데이터 저장
                players.append({
                    "Player": name,
                    "Club": team,
                    "Nation": nationality,
                    "Age": age,
                    "Market Value": market_value
                })

        else:
            print("Table not found on the page.")
            break
    else:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        break

    # 다음 페이지로 이동
    params["page"] += 1

# 데이터프레임 생성 및 출력 및 CSV 저장
if players:
    df = pd.DataFrame(players)
    df.index = df.index + 1  # 인덱스가 1부터 시작하도록 조정
    print(df.to_string(index=True))
    # CSV 파일 저장
    df.to_csv("transfermarket_o34_Goalkeeper_top50.csv", index=False, encoding="utf-8-sig")
    print("Data saved to 'transfermarket_o34_Goalkeeper_top50.csv'")
else:
    print("No players found.")

                Player                Club              Nation Age Market Value
1         David de Gea               Spain               Spain  34       €5.00m
2          Yann Sommer         Switzerland         Switzerland  35       €5.00m
3          Kevin Trapp             Germany             Germany  34       €4.00m
4         Manuel Neuer             Germany             Germany  38       €4.00m
5         Jason Steele             England             England  34       €3.50m
6      Lars Unnerstall             Germany             Germany  34       €3.50m
7        Péter Gulácsi             Hungary             Hungary  34       €3.00m
8       Oliver Baumann             Germany             Germany  34       €3.00m
9    Wojciech Szczęsny              Poland              Poland  34       €3.00m
10        Dénes Dibusz             Hungary             Hungary  34       €2.50m
11                Neto              Brazil              Brazil  35       €2.50m
12  Pietro Terracciano               Italy               Italy  34       €2.50m
13         Roman Bürki         Switzerland         Switzerland  34       €2.50m
14      Lukas Hradecky             Finland             Finland  35       €2.50m
15       Anthony Moris          Luxembourg          Luxembourg  34       €2.00m
16      Simon Mignolet             Belgium             Belgium  36       €2.00m
17  Mohamed El Shenawy               Egypt               Egypt  35       €1.80m
18            Weverton              Brazil              Brazil  36       €1.80m
19         Andre Blake             Jamaica             Jamaica  34       €1.50m
20             Everson              Brazil              Brazil  34       €1.50m
21         Robin Olsen              Sweden              Sweden  34       €1.50m
22       Camilo Vargas            Colombia            Colombia  35       €1.50m
23       Anthony Lopes            Portugal            Portugal  34       €1.50m
24        Ørjan Nyland              Norway              Norway  34       €1.40m
25       Pedro Gallese                Peru                Peru  34       €1.20m
26      Fraser Forster             England             England  36       €1.20m
27          Mert Günok             Türkiye             Türkiye  35       €1.20m
28         Hugo Lloris              France              France  37       €1.20m
29    Fernando Muslera             Uruguay             Uruguay  38       €1.10m
30        Helton Leite              Brazil              Brazil  34       €1.00m
31    Jasper Cillessen         Netherlands         Netherlands  35       €1.00m
32        Sean Johnson       United States       United States  35       €1.00m
33       Franco Armani           Argentina           Argentina  38       €1.00m
34        Keylor Navas          Costa Rica          Costa Rica  37       €1.00m
35     Martin Dúbravka            Slovakia            Slovakia  35       €1.00m
36        Rui Patrício            Portugal            Portugal  36       €1.00m
37     Guillermo Ochoa              Mexico              Mexico  39       €1.00m
38       Igor Akinfeev              Russia              Russia  38       €1.00m
39          Anas Zniti             Morocco             Morocco  36        €900k
40     Munir El Kajoui             Morocco             Morocco  35        €850k
41      Jaume Doménech               Spain               Spain  34        €800k
42              Santos              Brazil              Brazil  34        €800k
43       Hugo González              Mexico              Mexico  34        €800k
44      Vicente Guaita               Spain               Spain  37        €800k
45       Gabriel Arias               Chile               Chile  37        €800k
46       Seung-gyu Kim        Korea, South        Korea, South  34        €750k
47              Rafael              Brazil              Brazil  35        €750k
48       Ibrahim Sehic  Bosnia-Herzegovina  Bosnia-Herzegovina  36        €750k
49   Kasper Schmeichel             Denmark             Denmark  38        €750k
50      Miguel Jiménez              Mexico              Mexico  34        €700k
Data saved to 'transfermarket_o34_Goalkeeper_top50.csv'

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL 설정
base_url = "https://www.transfermarkt.com/spieler-statistik/wertvollstespieler/marktwertetop"
params = {
    "land_id": "0",
    "ausrichtung": "Abwehr",
    "spielerposition_id": "alle",
    "altersklasse": "o34",
    "jahrgang": "0",
    "kontinent_id": "0",
    "page": 1  # 페이지 번호 추가
}
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
}

# 데이터를 저장할 리스트 생성
players = []

# 여러 페이지 크롤링
while len(players) < 50:
    response = requests.get(base_url, headers=headers, params=params)

    # 상태 코드 확인
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, "html.parser")

        # 테이블 찾기
        table = soup.find("table", class_="items")

        if table:
            rows = table.find_all("tr", class_=["odd", "even"])
            for row in rows:
                if len(players) >= 50:
                    break

                # 선수 이름
                name_tag = row.find("td", class_="hauptlink")
                name = name_tag.a.get_text(strip=True) if name_tag and name_tag.a else "N/A"

                # 소속팀
                team_tag = row.find_all("td", class_="zentriert")[2]
                team = team_tag.img["alt"] if team_tag and team_tag.img else "N/A"

                # 국적
                nationality_tag = row.find("img", class_="flaggenrahmen")
                nationality = nationality_tag["alt"] if nationality_tag else "N/A"

                # 나이
                age_tag = row.find_all("td", class_="zentriert")[1]  # 두 번째 "zentriert" 클래스가 나이 열임
                age = age_tag.get_text(strip=True) if age_tag else "N/A"

                # 시장 가치
                market_value_tag = row.find("td", class_="rechts hauptlink")
                market_value = market_value_tag.get_text(strip=True) if market_value_tag else "N/A"

                # 데이터 저장
                players.append({
                    "Player": name,
                    "Club": team,
                    "Nation": nationality,
                    "Age": age,
                    "Market Value": market_value
                })

        else:
            print("Table not found on the page.")
            break
    else:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        break

    # 다음 페이지로 이동
    params["page"] += 1

# 데이터프레임 생성 및 출력 및 CSV 저장
if players:
    df = pd.DataFrame(players)
    df.index = df.index + 1  # 인덱스가 1부터 시작하도록 조정
    print(df.to_string(index=True))
    # CSV 파일 저장
    df.to_csv("transfermarket_o34_Defender_top50.csv", index=False, encoding="utf-8-sig")
    print("Data saved to 'transfermarket_o34_Defender_top50.csv'")
else:
    print("No players found.")

                 Player              Club            Nation Age Market Value
1           Kyle Walker           England           England  34      €13.00m
2       Kieran Trippier           England           England  34      €10.00m
3          Mats Hummels           Germany           Germany  35       €5.00m
4        Matteo Darmian             Italy             Italy  35       €4.00m
5      Francesco Acerbi             Italy             Italy  36       €3.50m
6           Axel Witsel           Belgium           Belgium  35       €3.50m
7          Romain Saïss           Morocco           Morocco  34       €3.00m
8       Nacho Fernández             Spain             Spain  34       €3.00m
9           Daley Blind       Netherlands       Netherlands  34       €3.00m
10    Toby Alderweireld           Belgium           Belgium  35       €2.80m
11          David López             Spain             Spain  35       €2.50m
12       Chris Smalling           England           England  35       €2.50m
13         Rafael Tolói             Italy             Italy  34       €2.50m
14           Jordi Alba             Spain             Spain  35       €2.50m
15          Jesús Navas             Spain             Spain  39       €2.50m
16     Gabriel Paulista            Brazil            Brazil  34       €2.00m
17         Craig Dawson           England           England  34       €2.00m
18     Sebastián Coates           Uruguay           Uruguay  34       €2.00m
19    César Azpilicueta             Spain             Spain  35       €2.00m
20          Jonny Evans  Northern Ireland  Northern Ireland  36       €2.00m
21       Yuri Berchiche             Spain             Spain  34       €1.80m
22         Sergio Ramos             Spain             Spain  38       €1.80m
23              Ismaily            Brazil            Brazil  34       €1.50m
24      Óscar de Marcos             Spain             Spain  35       €1.50m
25       Jan Vertonghen           Belgium           Belgium  37       €1.50m
26          Raúl Albiol             Spain             Spain  39       €1.50m
27      Stefan Mitrovic            Serbia            Serbia  34       €1.30m
28  Patrick van Aanholt       Netherlands       Netherlands  34       €1.20m
29      Álvaro González             Spain             Spain  34       €1.00m
30        Cristian Lema         Argentina         Argentina  34       €1.00m
31       Lisandro López         Argentina         Argentina  35       €1.00m
32        Guido Pizarro         Argentina         Argentina  34       €1.00m
33      Mário Fernandes            Russia            Russia  34       €1.00m
34            Joel Ward           England           England  35       €1.00m
35              Ben Mee           England           England  35       €1.00m
36    Danilo D'Ambrosio             Italy             Italy  36       €1.00m
37     Nicolás Otamendi         Argentina         Argentina  36       €1.00m
38                Zanka           Denmark           Denmark  34       €1.00m
39           Simon Kjær           Denmark           Denmark  35       €1.00m
40         Domagoj Vida           Croatia           Croatia  35       €1.00m
41              Marcelo            Brazil            Brazil  36       €1.00m
42         Dejan Lovren           Croatia           Croatia  35       €1.00m
43      Aaron Cresswell           England           England  34        €900k
44       Michael Ngadeu          Cameroon          Cameroon  34        €800k
45    Carlos Izquierdoz         Argentina         Argentina  36        €800k
46        Javier Aquino            Mexico            Mexico  34        €800k
47       Luis Advíncula              Peru              Peru  34        €800k
48          Marcos Rojo         Argentina         Argentina  34        €800k
49     Simone Romagnoli             Italy             Italy  34        €800k
50                 Cote             Spain             Spain  35        €800k
Data saved to 'transfermarket_o34_Defender_top50.csv'

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL 설정
base_url = "https://www.transfermarkt.com/spieler-statistik/wertvollstespieler/marktwertetop"
params = {
    "land_id": "0",
    "ausrichtung": "Mittelfeld",
    "spielerposition_id": "alle",
    "altersklasse": "o34",
    "jahrgang": "0",
    "kontinent_id": "0",
    "page": 1  # 페이지 번호 추가
}
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
}

# 데이터를 저장할 리스트 생성
players = []

# 여러 페이지 크롤링
while len(players) < 50:
    response = requests.get(base_url, headers=headers, params=params)

    # 상태 코드 확인
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, "html.parser")

        # 테이블 찾기
        table = soup.find("table", class_="items")

        if table:
            rows = table.find_all("tr", class_=["odd", "even"])
            for row in rows:
                if len(players) >= 50:
                    break

                # 선수 이름
                name_tag = row.find("td", class_="hauptlink")
                name = name_tag.a.get_text(strip=True) if name_tag and name_tag.a else "N/A"

                # 소속팀
                team_tag = row.find_all("td", class_="zentriert")[2]
                team = team_tag.img["alt"] if team_tag and team_tag.img else "N/A"

                # 국적
                nationality_tag = row.find("img", class_="flaggenrahmen")
                nationality = nationality_tag["alt"] if nationality_tag else "N/A"

                # 나이
                age_tag = row.find_all("td", class_="zentriert")[1]  # 두 번째 "zentriert" 클래스가 나이 열임
                age = age_tag.get_text(strip=True) if age_tag else "N/A"

                # 시장 가치
                market_value_tag = row.find("td", class_="rechts hauptlink")
                market_value = market_value_tag.get_text(strip=True) if market_value_tag else "N/A"

                # 데이터 저장
                players.append({
                    "Player": name,
                    "Club": team,
                    "Nation": nationality,
                    "Age": age,
                    "Market Value": market_value
                })

        else:
            print("Table not found on the page.")
            break
    else:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        break

    # 다음 페이지로 이동
    params["page"] += 1

# 데이터프레임 생성 및 출력 및 CSV 저장
if players:
    df = pd.DataFrame(players)
    df.index = df.index + 1  # 인덱스가 1부터 시작하도록 조정
    print(df.to_string(index=True))
    # CSV 파일 저장
    df.to_csv("transfermarket_o34_Midfielder_top50.csv", index=False, encoding="utf-8-sig")
    print("Data saved to 'transfermarket_o34_Midfielder_top50.csv'")
else:
    print("No players found.")

                 Player                Club              Nation Age Market Value
1        İlkay Gündoğan             Germany             Germany  34      €12.00m
2        Benjamin André              France              France  34       €6.00m
3    Henrikh Mkhitaryan             Armenia             Armenia  35       €6.00m
4           Luka Modric             Croatia             Croatia  39       €6.00m
5            Marco Reus             Germany             Germany  35       €5.00m
6      Jordan Henderson             England             England  34       €4.00m
7   Georginio Wijnaldum         Netherlands         Netherlands  34       €4.00m
8           Kevin Kampl            Slovenia            Slovenia  34       €3.50m
9          Ivan Rakitic             Croatia             Croatia  36       €3.50m
10         Rémy Cabella              France              France  34       €3.00m
11  Giacomo Bonaventura               Italy               Italy  35       €3.00m
12       Miralem Pjanic  Bosnia-Herzegovina  Bosnia-Herzegovina  34       €3.00m
13        Nemanja Matic              Serbia              Serbia  36       €2.50m
14     Taras Stepanenko             Ukraine             Ukraine  35       €2.50m
15          Dani Parejo               Spain               Spain  35       €2.50m
16  Grzegorz Krychowiak              Poland              Poland  34       €2.50m
17        Idrissa Gueye             Senegal             Senegal  35       €2.00m
18       Héctor Herrera              Mexico              Mexico  34       €2.00m
19        Ander Herrera               Spain               Spain  35       €2.00m
20      Sergio Busquets               Spain               Spain  36       €2.00m
21     Darlington Nagbe       United States       United States  34       €1.80m
22      Everton Ribeiro              Brazil              Brazil  35       €1.80m
23      Nacho Fernández           Argentina           Argentina  34       €1.80m
24          Dani García               Spain               Spain  34       €1.50m
25        Darko Lazović              Serbia              Serbia  34       €1.50m
26     Federico Lértora           Argentina           Argentina  34       €1.30m
27          Éver Banega           Argentina           Argentina  36       €1.30m
28      Younès Belhanda             Morocco             Morocco  34       €1.20m
29        Mateusz Klich              Poland              Poland  34       €1.20m
30     Charles Aránguiz               Chile               Chile  35       €1.20m
31      Nicolás Lodeiro             Uruguay             Uruguay  35       €1.20m
32       Rafael Carioca              Brazil              Brazil  35       €1.20m
33   Asier Illarramendi               Spain               Spain  34       €1.20m
34       Dani Rodríguez               Spain               Spain  36       €1.00m
35        Juan Cuadrado            Colombia            Colombia  36       €1.00m
36         Iván Marcone           Argentina           Argentina  34       €1.00m
37       Franco Vázquez           Argentina           Argentina  35       €1.00m
38       Nicolas Höfler             Germany             Germany  34       €1.00m
39             Fernando              Brazil              Brazil  37       €1.00m
40       Moussa Sissoko              France              France  35       €1.00m
41        Javi Martínez               Spain               Spain  36       €1.00m
42         Adam Lallana             England             England  36       €1.00m
43        Dimitri Payet              France              France  37       €1.00m
44          Oscar Trejo           Argentina           Argentina  36       €1.00m
45      Andrés Guardado              Mexico              Mexico  38       €1.00m
46         James Milner             England             England  38       €1.00m
47         Guélor Kanga               Gabon               Gabon  34        €900k
48          Fayçal Fajr             Morocco             Morocco  36        €900k
49            Edenilson              Brazil              Brazil  34        €900k
50              Eduardo              Brazil              Brazil  35        €900k
Data saved to 'transfermarket_o34_Midfielder_top50.csv'

In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL 설정
base_url = "https://www.transfermarkt.com/spieler-statistik/wertvollstespieler/marktwertetop"
params = {
    "land_id": "0",
    "ausrichtung": "Sturm",
    "spielerposition_id": "alle",
    "altersklasse": "o34",
    "jahrgang": "0",
    "kontinent_id": "0",
    "page": 1  # 페이지 번호 추가
}
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
}

# 데이터를 저장할 리스트 생성
players = []

# 여러 페이지 크롤링
while len(players) < 50:
    response = requests.get(base_url, headers=headers, params=params)

    # 상태 코드 확인
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, "html.parser")

        # 테이블 찾기
        table = soup.find("table", class_="items")

        if table:
            rows = table.find_all("tr", class_=["odd", "even"])
            for row in rows:
                if len(players) >= 50:
                    break

                # 선수 이름
                name_tag = row.find("td", class_="hauptlink")
                name = name_tag.a.get_text(strip=True) if name_tag and name_tag.a else "N/A"

                # 소속팀
                team_tag = row.find_all("td", class_="zentriert")[2]
                team = team_tag.img["alt"] if team_tag and team_tag.img else "N/A"

                # 국적
                nationality_tag = row.find("img", class_="flaggenrahmen")
                nationality = nationality_tag["alt"] if nationality_tag else "N/A"

                # 나이
                age_tag = row.find_all("td", class_="zentriert")[1]  # 두 번째 "zentriert" 클래스가 나이 열임
                age = age_tag.get_text(strip=True) if age_tag else "N/A"

                # 시장 가치
                market_value_tag = row.find("td", class_="rechts hauptlink")
                market_value = market_value_tag.get_text(strip=True) if market_value_tag else "N/A"

                # 데이터 저장
                players.append({
                    "Player": name,
                    "Club": team,
                    "Nation": nationality,
                    "Age": age,
                    "Market Value": market_value
                })

        else:
            print("Table not found on the page.")
            break
    else:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        break

    # 다음 페이지로 이동
    params["page"] += 1

# 데이터프레임 생성 및 출력 및 CSV 저장
if players:
    df = pd.DataFrame(players)
    df.index = df.index + 1  # 인덱스가 1부터 시작하도록 조정
    print(df.to_string(index=True))
    # CSV 파일 저장
    df.to_csv("transfermarket_o34_Forward_top50.csv", index=False, encoding="utf-8-sig")
    print("Data saved to 'transfermarket_o34_Forward_top50.csv'")
else:
    print("No players found.")

                       Player                  Club                Nation Age Market Value
1                Lionel Messi             Argentina             Argentina  37      €25.00m
2          Robert Lewandowski                Poland                Poland  36      €15.00m
3           Cristiano Ronaldo              Portugal              Portugal  39      €15.00m
4               Karim Benzema                France                France  36      €10.00m
5               Thomas Müller               Germany               Germany  35       €8.00m
6               Danny Welbeck               England               England  34       €5.00m
7   Pierre-Emerick Aubameyang                 Gabon                 Gabon  35       €5.00m
8                      Joselu                 Spain                 Spain  34       €4.50m
9           Wissam Ben Yedder                France                France  34       €4.00m
10            Michail Antonio               Jamaica               Jamaica  34       €4.00m
11           Marko Arnautovic               Austria               Austria  35       €4.00m
12              Ciro Immobile                 Italy                 Italy  34       €3.80m
13               Luuk de Jong           Netherlands           Netherlands  34       €3.50m
14                Dusan Tadic                Serbia                Serbia  36       €3.20m
15             Olivier Giroud                France                France  38       €3.00m
16                 Iago Aspas                 Spain                 Spain  37       €3.00m
17             Ángel Di María             Argentina             Argentina  36       €3.00m
18                Luis Suárez               Uruguay               Uruguay  37       €3.00m
19             Florian Sotoca                France                France  34       €2.50m
20             Yacine Brahimi               Algeria               Algeria  34       €2.50m
21          Christian Benteke               Belgium               Belgium  34       €2.50m
22             Alexis Sánchez                 Chile                 Chile  35       €2.50m
23                 Edin Dzeko    Bosnia-Herzegovina    Bosnia-Herzegovina  38       €2.50m
24                 Edin Visca    Bosnia-Herzegovina    Bosnia-Herzegovina  34       €2.20m
25             Enner Valencia               Ecuador               Ecuador  35       €2.00m
26          Andriy Yarmolenko               Ukraine               Ukraine  35       €2.00m
27                    Willian                Brazil                Brazil  36       €2.00m
28               Fedor Smolov                Russia                Russia  34       €2.00m
29               Artem Dzyuba                Russia                Russia  36       €2.00m
30               Ivan Perisic               Croatia               Croatia  35       €2.00m
31               Raúl Ruidíaz                  Peru                  Peru  34       €1.80m
32           Cristhian Stuani               Uruguay               Uruguay  38       €1.80m
33              Dries Mertens               Belgium               Belgium  37       €1.80m
34   Eric-Maxim Choupo-Moting              Cameroon              Cameroon  35       €1.80m
35          Gianluca Lapadula                  Peru                  Peru  34       €1.50m
36             Eduardo Salvio             Argentina             Argentina  34       €1.50m
37                       Hulk                Brazil                Brazil  38       €1.50m
38               Milan Djuric    Bosnia-Herzegovina    Bosnia-Herzegovina  34       €1.50m
39             Gabriel Ávalos              Paraguay              Paraguay  34       €1.30m
40           Anthony Nwakaeme               Nigeria               Nigeria  35       €1.30m
41               Ali Mabkhout  United Arab Emirates  United Arab Emirates  34       €1.30m
42               Odion Ighalo               Nigeria               Nigeria  35       €1.30m
43              Islam Slimani               Algeria               Algeria  36       €1.20m
44                Carlos Vela                Mexico                Mexico  35       €1.20m
45          José Luis Morales                 Spain                 Spain  37       €1.00m
46                Jamie Vardy               England               England  37       €1.00m
47                Kike García                 Spain                 Spain  35       €1.00m
48    Jóhann Berg Gudmundsson               Iceland               Iceland  34       €1.00m
49             Salomón Rondón             Venezuela             Venezuela  35       €1.00m
50                      Pedro                 Spain                 Spain  37       €1.00m
Data saved to 'transfermarket_o34_Forward_top50.csv'